[url_api]
URL_API="https://tweet911-4fzvna7zgq-ew.a.run.app"

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1dKk9aTcpV0UjQi6NxGYFwG60cqIZxgm9SwBIZAr5kNg/edit?usp=sharing"
